server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.yrcejvckguemomakvwmf&password=sydtNSKGV9SrxxmU

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

github.api.base-url=https://api.github.com
github.api.token=